# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20160206_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('series__name', 'title', 'year')},
        ),
        migrations.DeleteModel(
            name='BookProfile',
        ),
    ]
