# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160130_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('series__name', 'publisher__name', 'author__name', 'title', 'year')},
        ),
    ]
