# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160201_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprofile',
            name='import_root',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
