# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160123_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='The title', max_length=256),
            preserve_default=False,
        ),
    ]
