# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 16:28
from __future__ import unicode_literals

from django.db import migrations

from rest_framework.authtoken.models import Token


def add_tokens(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        Token.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160123_0722'),
    ]

    operations = [
        migrations.RunPython(add_tokens)
    ]
