# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20160317_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dropbox_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
