# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20160410_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dropbox_id',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
